### ISSUE TITLE
Exam Bank: Frontend Page Design

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#101]
This will be a new page for Exam Bank. The existing Exam bank page can be found here:
https://services.mathsoc.uwaterloo.ca/university/exambank

We want a more modern. The page will have the follow requirements:

Users should be able to select Course type (STATS, CS, MATH, etc) then be able to select the course #
Once the course is selected, a list of exams should be populated

**Comment by mathSocVPO** [comment]
This will be a new page for Exam Bank. The existing Exam bank page can be found here:
https://services.mathsoc.uwaterloo.ca/university/exambank

We want a more modern. The page will have the follow requirements:

- Users should be able to select Course type (STATS, CS, MATH, etc) then be able to select the course #
- Once the course is selected, a list of exams should be populated

**Comment by some-molasses** [comment]
Should this be pushed to version two?  We have the exam bank mostly built and designed already https://github.com/MathSoc/mathsoc-website/pull/104, but we could rebuild it again once we have the bandwidth to do so.

**Comment by some-molasses** [comment]
Closing because stale; we can catch this as part of the future redesign sweeps
