### ISSUE TITLE
Wordpress: Update the Budgets Page

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#108]
We want the budgets page to be updated to included all the latest MathSoc Budgets. The missing budgets are the following:

Winter 2022: https://docs.google.com/spreadsheets/d/1cR8FNZ94yIusIi4xw4BXq4AxUz2u-Fum/edit?usp=sharing&ouid=102748935011808695637&rtpof=true&sd=true
Spring: 2022: https://docs.google.com/spreadsheets/d/1dKoIbdCI21XApBRWildiMFAta_eEDsFR/edit?usp=sharing&ouid=102748935011808695637&rtpof=true&sd=true
Fall 2022: https://docs.google.com/spreadsheets/d/1were4z5rKAkrVg0TDZHgEbV7ibkDbImI/edit?usp=sharing&ouid=102748935011808695637&rtpof=true&sd=true
Winter 2023: https://docs.google.com/spreadsheets/d/1-l8Jiwkk_-8al5NFx4rs_8Pk0XSZBE22/edit?usp=sharing&ouid=102748935011808695637&rtpof=true&sd=true

**Comment by eysix** [comment]
https://mathsoc.uwaterloo.ca/budgets/
