### ISSUE TITLE
Wordpress: Remove the Work Term Reports Page

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#109]
This page is now redundant since we no longer have to write work term reports as Math Students. We can either remove the page entirely or update it so that it talks about how the past VPA had work term reports removed.

https://mathsoc.uwaterloo.ca/work-term-report/

**Comment by eysix** [comment]
@mathSocVPO Is there more information on the removal of work term reports?

**Comment by some-molasses** [comment]
Closed due to being done
