### ISSUE TITLE
MathSoc Clubs: Add Math Studies Club

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#124]
Link to their IG: uwmathstudies 

Use this as bio: 
Presenting MathSoc’s new club, the Math Studies Club! Our club is for the math studies majors or the undeclared students. We hope to become the first "step" for new Math students in becoming involved with the math clubs, and even if you choose another major, we'll always be here! 

Math Studies is the major for those who want to take all sorts of courses, or the official "undeclared" major. Come join us and be part of building the club culture with others that also have all sorts of interests in the math field, or with others who also don’t know what major to take!

**Comment by some-molasses** [comment]
Closing since it is done
