### ISSUE TITLE
Static page: Volunteer at Mathsoc 

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#17]
Redevelop https://mathsoc.uwaterloo.ca/volunteer-at-mathsoc/ for the new site.

**Acceptance criteria:** The page is rebuilt, containing all information from the version on the old site.

**Comment by jinitsuga** [comment]
Hi - I see new issues open, but there isn't much info about them in their descriptions. Correct me if I'm wrong, but it seems like you're re-developing the entire website. What tech stack are you intending to use? And going off of what design? I'm open to help if needed.

**Comment by some-molasses** [comment]
> Hi - I see new issues open, but there isn't much info about them in their descriptions. Correct me if I'm wrong, but it seems like you're re-developing the entire website. What tech stack are you intending to use? And going off of what design? I'm open to help if needed.

Hello, thank you for offer, but we must decline.  We plan to keep contributors to this project limited to developers within the University of Waterloo Math Society, where we have a student web development team working on building this repository.
