### ISSUE TITLE
Pages: Community links and MathSoc clubs

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#18]
Redevelop https://mathsoc.uwaterloo.ca/get-involved/ and https://mathsoc.uwaterloo.ca/clubs/ for the new site.

**Acceptance criteria:** The pages are rebuilt, containing all information from the version on the old site.

**Comment by mathSocVPO** [comment]
Recreate the MathSoc Clubs page as follows:
https://mathsoc.uwaterloo.ca/clubs/

Be sure that the club website links are working. If the link is broken, try finding their website by searching on google "UW "

No additional content needs to be added to this page.

We want the Community Links page to get recreated:
https://mathsoc.uwaterloo.ca/get-involved/

This page is for MathSoc's affiliates. Each image is a link to the associated affiliate's website. This page doesn't need to be redesigned.

Additional Content:
Please add one more Link for MathSoc Cartoons, have their image link to the Cartoons page.
