### ISSUE TITLE
CMS Editor: Handle numbers

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#208]
There's a bug we need to fix around the admin editor.

**Steps to replicate:**

1. Open http://localhost:3000/admin/editor?page=resources/meetings.json
2. Try updating the value of a meeting's term number (i.e. 1231 -> 12313) (see pictured)
 
![image](https://github.com/MathSoc/mathsoc-website/assets/37753525/85bfb2bd-4419-497b-b6a6-765c5d751e0d)

3. Press save.
4. Note that rather than successfully saving, an error is thrown. If you go into the Network tab of your devtools and look at the response under http://localhost:3000/admin/editor?page=resources/meetings, you'll see why. The backend expected a number for the term number, but received a string.

This is because the EditorLabelNode only handles strings at the moment. It's our fallback for all non-object data types, so even though the term number is a number, we're using `EditorLabelNode` anyway.

**Steps to solve:**

Either we can change the behaviour of the `EditorLabelNode` to handle numbers, or we can add a new `EditorNode` subclass using the same underlying component. I'm a fan of the new subclass option.

**Comment by ShreyaLizAntony** [comment]
Hi, I would like to work on this issue. Can I have it assigned to me? Thanks!

**Comment by KuroganeToyama** [comment]
Hey @some-molasses , I'm deploying the website from the main branch and I'm not seeing the Meetings section on the admin view.

When I go to http://localhost:8000/admin/editor?page=documents/meetings.json, I only see this

![image](https://github.com/user-attachments/assets/6d787301-a19c-4ee4-9e40-502e308160b5)

Was wondering if you could provide some insights.

**Comment by some-molasses** [comment]
oops, that's because we renamed the parent item for the meetings page from "documents" to "resources"

try http://localhost:3000/admin/editor?page=resources/meetings.json !

**Comment by KuroganeToyama** [comment]
Hi @some-molasses, the new URL worked, so thanks! Though I now have another question. Where can I find the `EditorLabelNode` class?

**Comment by some-molasses** [comment]
![image](https://github.com/user-attachments/assets/455bb54f-1378-4f87-9037-d125b2edc9ee)

it should be visible in your IDE's search function! you can find it under `public/assets/ts/page-editor/editor-nodes/EditorLabelNode.tsx`

**Comment by KuroganeToyama** [comment]
Found it, thanks!

**Comment by KuroganeToyama** [comment]
So I fixed the issue, by slightly tuning the behavior of the class, i.e. by checking if the input can be parsed as a number, and cast the type accordingly if it is. It was a rather simple fix. So I'm curious about why you prefer to have a separate class.

**Comment by some-molasses** [comment]
lol that's a good point.

the key issue is that we need the type returned to the backend to match what it expects (as defined in `schemas.ts`) (if you search for "`z.object`" you can find the file). Right now, there's numerical fields that are being sent strings from the frontend, and then rejecting them.

The main worry I can see for "if parsable as number, send a number" is that there's also string fields where the user could theoretically set them to a number-parseable value. (example: if we had a "price" field, stored as a string for flexibility, where the user set the value to "2.00"). This would also fail validation; the backend expects a string, but would be sent a number.

There's an endpoint somewhere to return the schema of the data file - if we could make the node use that as its reference of "is this a string or a number," we should be able to circumvent those issues. You're 100% right that a new node isn't necessary, we just need to make sure our string/number decisioning is correct!

**Comment by KuroganeToyama** [comment]
I see your point now. I'll admit that I didn't imagine those situations. And now that you have mentioned them, I'd say it's a better idea to build a separate component to only handle numbers. Should make things more modular and reusable as well. I'll see if I can't cook something up.
