### ISSUE TITLE
CMS Editor: Handle Mathsoc Office items

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#210]
In the backend editor, the Mathsoc Office page's item price list can't have new items added.

![image](https://github.com/MathSoc/mathsoc-website/assets/37753525/4d87fd68-b2b7-4e23-a7a4-c4362f60cbcb)

**Steps to replicate:**
* Go to http://localhost:3000/admin/editor?page=services/mathsoc-office.json
* Try adding a new item, removing an item, renaming an item, etc. You can't :(

**Steps to solve:**
* Either we can switch the schema of this to use an object array, or we create a new `EditorNode` subclass to handle items and prices. I think changing the schema makes the most sense.

**Comment by ShreyaLizAntony** [comment]
Hi, I would like to work on this issue. Can I have it assigned to me? Thanks!
