### ISSUE TITLE
Add website request form to contact us page

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#212]
On the current site, we have a website request form where students can request changes to the site. It's available under https://mathsoc.uwaterloo.ca/website-requests/.

We don't need to copy this entire page to the new site, but we should still have this form on the site. Let's add it to the Contact Us page.

**Comment by SyedZain714** [comment]
@some-molasses I want to work on this issue.
Can you please explain me a bit about the page.
Do you want this whole page under Contact us?
