### ISSUE TITLE
Add "skip to main content" buttons

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#213]
On most webpages, including this github page, "skip to main content" button is included to allow keyboard-only users to navigate the site easier. It generally appears when they first press `tab` on a page, as the first focusable button onscreen. Try using `tab` and `shift+tab` to find it on this page for yourself.

We should have a similar button on the Mathsoc site.

* Add a "skip to main content" button on all pages to skip over the navbar.
* Add a "skip sidebar" button on the admin editor to skip over the Editor Select sidebar.

feel free to reach out for clarifications :)

**Comment by joannamooon** [comment]
taking!
