### ISSUE TITLE
Elections page - Handle no election

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#220]
![image](https://github.com/MathSoc/mathsoc-website/assets/37753525/749879b3-d40a-47bf-8881-a9b587b5bc26)

With a fresh clone of the repository, the above error appears. oops.

In the event that there's no election data, we should have the elections page either 
1) not exist and be removed from the navbar, or 
2) display a message to the effect of "There appears to be no election information at the moment. Check back later"

**Comment by N-Hioe** [comment]
Don't think if I have self-assigning privileges, but planning to take this ticket.

**Comment by some-molasses** [comment]
done
