### ISSUE TITLE
Page: "Linktree"

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#23]
To help future MathSoc VPs and Execs to centralize information and prevent duplication of work, let's create a centralized "Linktree" page that replaces the need for MathSoc web presences like Instagram to use solutions like https://linktr.ee/mathsocuw.  In particular, this helps to ensure that any information on the website is also available to Instagram users, and any information available to Instagram users is also available on the website.  (In contrast, the current linktree at time of writing contains many links not visible to web visitors).

Sample design:

<img src="https://user-images.githubusercontent.com/37753525/203636453-403f5766-2f7d-48f9-b412-87805f2fca8f.png" width="50%">

**Acceptance criteria:**
* We have a centralized location for important links, which can easily be linked to from social media platforms such as the Instagram bio.
* Links can be added, removed, edited, etc. from within the CMS

**Comment by gavinxue050705** [comment]
Hi I would like to be assigned this issue.
