### ISSUE TITLE
Council page - Mailing list signup - Frontend

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#269]
We should replicate the mailing list signup available on https://mathsoc.uwaterloo.ca/council/.

This might take some investigation into how things work on the existing site - a web dev lead can help with this.

**Acceptance criteria:**
* When I navigate to the council page
* There is a 'Sign up for the mailing list' button, with an input field that allows me to enter my email

**Comment by KuroganeToyama** [comment]
Hey there, I think I'd like to work on this issue.
