### ISSUE TITLE
Exam bank - re-add navbar

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#276]
![image](https://github.com/user-attachments/assets/065c4671-f99a-48c2-bc81-e858f7875774)

At the moment, setting `EXAM_BANK_ONLY=true` in the `.env` file removes the navbar entirely. This doesn't look great - let's re-add the navbar, but ensure there's no menu items on it when `EXAM_BANK_ONLY=true`.

**Comment by Andoiiii** [comment]
I've made the changes, now the mathsoc logo alone (with the navbar background!) shows up in both mobile and desktop resolutions.

One issue though - the logo's href doesn't work with the exam bank only option, since I think there isn't a mapping to "/"... is this ok?

**Comment by Andoiiii** [comment]
![image](https://github.com/user-attachments/assets/a9e7ed11-b5af-427a-9154-65b79b872d45)
