### ISSUE TITLE
CMS: Popup on form submission

### ISSUE THREAD

**Issue by some-molasses** [MathSoc/mathsoc-website#56]
On the backend, admin users currently have no indication that they've successfully submitted their data.  We should have some sort of popup that indicates the submission was successful.

One idea for how to do this visually (although always feel free to come up with your own improved designs): 

![image](https://user-images.githubusercontent.com/37753525/212243419-d1b62608-25f0-4c7d-bf30-47bfd6e36f1e.png)

**Acceptance criteria:**
* Upon pressing 'Update'/'Submit'/etc. on any form in the CMS, the admin user is notified that their submission was received.  
* This message _changes_ depending on whether the form submission returns a 2XX code (success) or 4XX/5XX code (failure).

**Comment by ad-world** [comment]
Couldn't we technically build this straight into the editor? Then it would be generalized for all cms pages that use the editor

**Comment by some-molasses** [comment]
We could!  I think we didn't have the JSON editor when I put together the design in the issue, that's why it's not there.

**Comment by ad-world** [comment]
Sounds good. I'm gonna assign this to myself, looks like good fun
