### ISSUE TITLE
Frontend: Get Involved - Community Links

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#97]
We want the Community Links page to get recreated: 
https://mathsoc.uwaterloo.ca/get-involved/

This page is for MathSoc's affiliates. Each image is a link to the associated affiliate's website. This page doesn't need to be redesigned. 

Additional Content:
Please add one more Link for MathSoc Cartoons, have their image link to the Cartoons page.

**Comment by some-molasses** [comment]
I think @alexandrawang1 is already working on this 😅

**Comment by mathSocVPO** [comment]
> I think @alexandrawang1 is already working on this 😅

Assigned it to her
