### ISSUE TITLE
Frontend: Get Involved - Clubs Page

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#98]
Recreate the MathSoc Clubs page as follows:
https://mathsoc.uwaterloo.ca/clubs/

Be sure that the club website links are working. If the link is broken, try finding their website by searching on google "UW <club name>" 

No additional content needs to be added to this page.

**Comment by some-molasses** [comment]
@alexandrawang1 is also working on this - the two pages were grouped into the first ticket she took on, since the structures of the two pages largely duplicate each other.

We should close this and #97 since it's already covered by #18.
