### ISSUE TITLE
Wordpress - Update Club Links

### ISSUE THREAD

**Issue by mathSocVPO** [MathSoc/mathsoc-website#99]
Update this page:
https://mathsoc.uwaterloo.ca/clubs/

The FARMSA website link doesn't work, needs to be updated to:
https://www.uwfarmsa.com/

TSA doesn't have a website and clicking it should redirect to their email:
tsa@uwaterloo.ca

**Comment by BT-H** [comment]
glad to do it if you assign it to me

**Comment by mathSocVPO** [comment]
@eysix for the datascience club link can you fix it so that it creates a new tab like how it does the for other clubs please?

**Comment by eysix** [comment]
Yup, just updated it
